name = "klean-41-car-race-collision"
version = "0.1.0"
defaultTargets = ["Klean41CarRaceCollision"]
weakLeanArgs = [
    "-D maxHeartbeats=10000000"
]

buildDir = "/tmp/klean-generated-build"

[[lean_lib]]
name = "Klean41CarRaceCollision"
