#!/usr/bin/env python3
"""Create a line-addressed inventory of the supplied and proof-local K theory."""

from __future__ import annotations

import re
from collections import Counter
from pathlib import Path


ROOT = Path("/tmp/audit-work/anti-shuffle")
FILES = [
    ROOT / "reference-semantics" / "semantics.k",
    *sorted((ROOT / "reference-semantics" / "semantics").glob("*.k")),
    ROOT / "program-generated.k",
    ROOT / "verification.k",
    ROOT / "spec.k",
    ROOT / "lemma-spec.k",
]
START = re.compile(
    r"^\s{2}(syntax|rule|context|configuration|claim)\b"
)
BOUNDARY = re.compile(
    r"^\s{0,2}(?:syntax|rule|context|configuration|claim|module|endmodule|"
    r"imports|requires)\b"
)
ATTR = re.compile(r"\[([^\]]+)\]")


def entries(path: Path):
    lines = path.read_text(encoding="utf-8").splitlines()
    starts = [i for i, line in enumerate(lines) if START.match(line)]
    for start in starts:
        kind = START.match(lines[start]).group(1)
        end = start + 1
        while end < len(lines) and not BOUNDARY.match(lines[end]):
            end += 1
        block_lines = [
            line.split("//", 1)[0].strip()
            for line in lines[start:end]
            if line.split("//", 1)[0].strip()
        ]
        block = " ".join(block_lines)
        attrs = ",".join(ATTR.findall(block)) or "-"
        flags = [
            flag
            for flag in (
                "function",
                "functional",
                "total",
                "simplification",
                "priority",
                "owise",
                "concrete",
                "no-evaluators",
                "macro",
                "macro-rec",
                "strict",
                "seqstrict",
            )
            if re.search(rf"\b{re.escape(flag)}\b", block)
        ]
        yield start + 1, kind, attrs, ",".join(flags) or "-", block


def decision(rel: Path, line: int, kind: str) -> str:
    rel_text = rel.as_posix()
    if rel_text == "reference-semantics/semantics/concrete.k":
        return "FIXED_BASE_LLVM_ONLY_NOT_IN_PROOF"
    if rel_text.startswith("reference-semantics/"):
        material_modules = {
            "reference-semantics/semantics/syntax.k",
            "reference-semantics/semantics/core.k",
            "reference-semantics/semantics/iter.k",
            "reference-semantics/semantics/str.k",
            "reference-semantics/semantics/controls.k",
            "reference-semantics/semantics/operators.k",
            "reference-semantics/semantics/bool.k",
            "reference-semantics/semantics/functions.k",
            "reference-semantics/semantics/call.k",
        }
        if rel_text in material_modules:
            return "FIXED_BASE_MATERIAL_MODULE"
        return "FIXED_BASE_PATTERN_UNREACHABLE"
    if rel_text == "program-generated.k":
        return "DEFINITIONAL_EXACT_REGENERATED"
    if rel_text == "verification.k":
        if line == 8:
            return "DERIVED_SINGLETON_ORDER_SOUND"
        if line in {16, 21, 35, 45, 58}:
            return "DEFINITIONAL_EXACT_SUBTERM"
        return "TOTAL_STRUCTURAL_SPEC_SOUND"
    if rel_text == "lemma-spec.k":
        return "BRIDGE_FREE_POSITIVE_CLAIM_PROVED"
    if rel_text == "spec.k":
        return "TARGET_REACHABILITY_CLAIM_PROVED"
    return "INVENTORIED"


def main() -> None:
    totals = Counter()
    rendered = []
    for path in FILES:
        rel = path.relative_to(ROOT)
        file_entries = list(entries(path))
        kinds = Counter(item[1] for item in file_entries)
        totals.update(kinds)
        rendered.append(
            f"\n## `{rel}`\n\n"
            f"Entries: {len(file_entries)} "
            + ", ".join(f"{kind}={count}" for kind, count in sorted(kinds.items()))
            + "\n"
        )
        for line, kind, attrs, flags, block in file_entries:
            rendered.append(
                f"\n- `{rel}:{line}` | `{kind}` | attrs `{attrs}` | "
                f"flags `{flags}` | decision `{decision(rel, line, kind)}` | "
                f"`{block}`"
            )
        rendered.append("\n")

    print("# K declaration and rule inventory")
    print()
    print(
        "Generated by `inventory_rules.py`. Each declaration/rule/context/claim "
        "is listed by source line; multiline declarations are flattened."
    )
    print()
    print(
        "Totals: "
        + ", ".join(f"{kind}={count}" for kind, count in sorted(totals.items()))
        + f"; all={sum(totals.values())}"
    )
    print("".join(rendered))


if __name__ == "__main__":
    main()
