name = "klean-138-is-equal-to-sum-even"
version = "0.1.0"
defaultTargets = ["Klean138IsEqualToSumEven"]
weakLeanArgs = [
    "-D maxHeartbeats=10000000"
]

buildDir = "/tmp/klean-generated-build"

[[lean_lib]]
name = "Klean138IsEqualToSumEven"
