name = "klean-162-string-to-md5"
version = "0.1.0"
defaultTargets = ["Klean162StringToMd5"]
weakLeanArgs = [
    "-D maxHeartbeats=10000000"
]

buildDir = "/tmp/klean-generated-build"
moreLeanArgs = ["-D maxRecDepth=100000", "-s", "65536"]

[[lean_lib]]
name = "Klean162StringToMd5"
