#!/usr/bin/env python3
"""Check the generated MD5 constant and shift tables independently."""

from __future__ import annotations

import hashlib
import math
from pathlib import Path
import re
import sys


SEMANTIC = Path("/tmp/audit-work/reconstruction/semantic.k")


def main() -> int:
    source = SEMANTIC.read_text(encoding="utf-8")
    parsed_constants = {
        int(index): int(value)
        for index, value in re.findall(
            r"^\s*rule\s+md5K\((\d+)\)\s*=>\s*(\d+)\s*$",
            source,
            re.MULTILINE,
        )
    }
    expected_constants = {
        index: math.floor(abs(math.sin(index + 1)) * (2**32))
        for index in range(64)
    }
    constant_errors = {
        index: (parsed_constants.get(index), expected_constants[index])
        for index in range(64)
        if parsed_constants.get(index) != expected_constants[index]
    }
    print(f"md5K parsed entries: {len(parsed_constants)}")
    for index in range(64):
        print(
            f"md5K({index}) parsed={parsed_constants.get(index)} "
            f"rfc_formula={expected_constants[index]} "
            f"match={parsed_constants.get(index) == expected_constants[index]}"
        )

    parsed_shifts: dict[int, int] = {}
    for line in source.splitlines():
        match = re.match(
            r"\s*rule md5Shift\(I\) => (\d+)\s+requires "
            r"I >=Int (\d+)\s+andBool I <Int (\d+) "
            r"andBool I modInt 4 ==Int (\d+)",
            line,
        )
        if match is None:
            continue
        shift, lower, upper, residue = map(int, match.groups())
        for index in range(lower, upper):
            if index % 4 == residue:
                if index in parsed_shifts:
                    print(f"ERROR: overlapping shift rule at index {index}")
                parsed_shifts[index] = shift
    round_patterns = [
        [7, 12, 17, 22],
        [5, 9, 14, 20],
        [4, 11, 16, 23],
        [6, 10, 15, 21],
    ]
    expected_shifts = {
        index: round_patterns[index // 16][index % 4] for index in range(64)
    }
    shift_errors = {
        index: (parsed_shifts.get(index), expected_shifts[index])
        for index in range(64)
        if parsed_shifts.get(index) != expected_shifts[index]
    }
    print(f"md5Shift covered indices: {len(parsed_shifts)}")
    print(f"md5Shift mismatches: {shift_errors}")

    # Independent RFC-style digest implementation exercises the audited
    # formula and table data over boundary and generated byte strings.
    def left_rotate(value: int, shift: int) -> int:
        value &= 0xFFFFFFFF
        return ((value << shift) | (value >> (32 - shift))) & 0xFFFFFFFF

    def rfc_md5(data: bytes) -> str:
        original_bit_length = (8 * len(data)) & 0xFFFFFFFFFFFFFFFF
        padded = data + b"\x80"
        padded += b"\x00" * ((56 - len(padded)) % 64)
        padded += original_bit_length.to_bytes(8, "little")
        a0, b0, c0, d0 = 0x67452301, 0xEFCDAB89, 0x98BADCFE, 0x10325476
        for offset in range(0, len(padded), 64):
            words = [
                int.from_bytes(padded[offset + 4 * j : offset + 4 * j + 4], "little")
                for j in range(16)
            ]
            a, b, c, d = a0, b0, c0, d0
            for index in range(64):
                if index < 16:
                    f = (b & c) | ((~b) & d)
                    g = index
                elif index < 32:
                    f = (d & b) | ((~d) & c)
                    g = (5 * index + 1) % 16
                elif index < 48:
                    f = b ^ c ^ d
                    g = (3 * index + 5) % 16
                else:
                    f = c ^ (b | (~d))
                    g = (7 * index) % 16
                a, b, c, d = (
                    d,
                    (b + left_rotate(a + f + expected_constants[index] + words[g], expected_shifts[index]))
                    & 0xFFFFFFFF,
                    b,
                    c,
                )
            a0 = (a0 + a) & 0xFFFFFFFF
            b0 = (b0 + b) & 0xFFFFFFFF
            c0 = (c0 + c) & 0xFFFFFFFF
            d0 = (d0 + d) & 0xFFFFFFFF
        return b"".join(
            word.to_bytes(4, "little") for word in (a0, b0, c0, d0)
        ).hex()

    inputs = [
        b"",
        b"a",
        b"Hello world",
        b"a" * 55,
        b"a" * 56,
        b"a" * 57,
        b"b" * 63,
        b"b" * 64,
        b"b" * 65,
        bytes(range(128)),
        bytes(range(256)),
        bytes((index * 73 + 19) % 256 for index in range(1024)),
    ]
    digest_errors = 0
    for data in inputs:
        actual = rfc_md5(data)
        expected = hashlib.md5(data).hexdigest()
        match = actual == expected
        digest_errors += 0 if match else 1
        print(
            f"rfc-md5 length={len(data)} actual={actual} "
            f"hashlib={expected} match={match}"
        )

    errors = len(constant_errors) + len(shift_errors) + digest_errors
    print(f"constant mismatches: {constant_errors}")
    print(f"total errors: {errors}")
    return 1 if errors else 0


if __name__ == "__main__":
    sys.exit(main())
