#!/usr/bin/env python3
"""Attach an explicit reachability/soundness decision to every inventory row."""

from __future__ import annotations

import csv
from collections import Counter
from pathlib import Path


SOURCE = Path("/audit-output/evidence/rule-inventory.tsv")
OUT = Path("/audit-output/evidence/rule-assessment.tsv")
SUMMARY = Path("/audit-output/evidence/rule-assessment-summary.txt")


def in_ranges(line: int, ranges: list[tuple[int, int]]) -> bool:
    return any(low <= line <= high for low, high in ranges)


# Source lines on the actual symbolic-execution path of the submitted closure.
USED_RANGES: dict[str, list[tuple[int, int]]] = {
    "syntax.k": [(9, 54)],
    "core.k": [
        (13, 60),
        (123, 191),
        (193, 205),
        (207, 240),
    ],
    "controls.k": [(8, 31), (46, 74)],
    "functions.k": [(8, 16), (62, 90)],
    "call.k": [(15, 31), (69, 75)],
    "tuple.k": [(30, 41)],
    "str.k": [(7, 17)],
    "methods.k": [(9, 16), (111, 130)],
    "builtins.k": [(12, 17), (142, 144)],
    "int.k": [(9, 12)],
}

GAP_RANGES: dict[str, list[tuple[int, int]]] = {
    "str.k": [(12, 17)],
    "methods.k": [(12, 16), (111, 130)],
}


rows: list[dict[str, str]] = []
with SOURCE.open() as stream:
    reader = csv.DictReader(stream, delimiter="\t")
    for row in reader:
        source = Path(row["source"])
        base = source.name
        line = int(row["line"])
        text = row["text"]
        code = row["code"]
        category = row["category"]

        if source.name == "verification.k":
            if category == "syntax-declaration":
                decision = "PROOF_LOCAL_SOUND_DEFINITION"
                reason = (
                    "digitSumIS only names the result; constructor equations are "
                    "disjoint, exhaustive over IntSeq, and structurally recursive"
                )
            elif category == "ordinary-rule":
                decision = "PROOF_LOCAL_SOUND_EQUATION"
                reason = (
                    "base/cons equation is ordinary integer mathematics and exactly "
                    "matches the fixed one-character isupper/ord path"
                )
            else:
                decision = "PROOF_LOCAL_STRUCTURAL"
                reason = "module/import structure has no rewrite conclusion"
        elif source.name == "spec.k":
            if category == "claim":
                decision = "PROVED_REACHABILITY_CLAIM"
                reason = (
                    "positive claim closes in the clean full proof; loop claim is "
                    "the fixed-semantics connection theorem and entry pins that body"
                )
            else:
                decision = "SPEC_STRUCTURAL"
                reason = "module/import structure has no rewrite conclusion"
        elif "reference-semantics" not in str(source):
            decision = "OUT_OF_SCOPE"
            reason = "not a supplied-semantics or proof source"
        elif category in {"module", "endmodule", "imports", "requires"}:
            decision = "FIXED_MODEL_STRUCTURAL"
            reason = "structural module/import/guard item; no standalone result rewrite"
        elif "no-evaluators" in code:
            decision = "OPAQUE_FIXED_UNUSED_NO_DEPENDENCY"
            reason = (
                "fixed supplied-model opaque symbol; absent from submitted program, "
                "both claims, digitSumIS, and every reachable term"
            )
        elif base in USED_RANGES and in_ranges(line, USED_RANGES[base]):
            if base in GAP_RANGES and in_ranges(line, GAP_RANGES[base]):
                decision = "USED_FIXED_MODEL_REPRESENTATION_GAP"
                reason = (
                    "sound for the supplied ASCII model but not full CPython Unicode; "
                    "the fixed model/literal bridge cannot represent the witnessed À case"
                )
            elif category == "syntax-declaration" and (
                "strict" in text or "seqstrict" in text
            ):
                decision = "USED_FIXED_AUTOGENERATED_EVALUATION"
                reason = (
                    "strictness generates the expected evaluation order for this "
                    "construct; all operands on the path are fixed-semantics values"
                )
            else:
                decision = "USED_FIXED_MODEL_SOUND"
                reason = (
                    "matches the selected model's binding/evaluation/control/value "
                    "transition on the submitted program path; no result oracle or bypass"
                )
        elif category in {
            "syntax-declaration",
            "configuration",
            "context",
        }:
            decision = "FIXED_MODEL_UNUSED_DECLARATION"
            reason = (
                "not reached by the submitted constructor term or proof claims; "
                "cannot contribute to their closure"
            )
        else:
            decision = "FIXED_MODEL_UNUSED_RULE"
            reason = (
                "LHS constructor/callee/operator is absent from all reachable submitted "
                "states; no dependency from either positive claim"
            )

        rows.append({**row, "decision": decision, "reason": reason})

with OUT.open("w", newline="") as stream:
    writer = csv.DictWriter(
        stream,
        fieldnames=list(rows[0]) if rows else [],
        delimiter="\t",
    )
    writer.writeheader()
    writer.writerows(rows)

counts = Counter(row["decision"] for row in rows)
with SUMMARY.open("w") as stream:
    stream.write(f"ASSESSED_ITEMS: {len(rows)}\n")
    stream.write("DECISION_COUNTS:\n")
    for key, value in sorted(counts.items()):
        stream.write(f"  {key}: {value}\n")
    stream.write("\nPROOF-DEPENDENT ITEMS:\n")
    for row in rows:
        if row["decision"].startswith(
            (
                "PROOF_LOCAL",
                "PROVED",
                "USED_FIXED",
            )
        ):
            stream.write(
                f"{row['source']}:{row['line']} [{row['decision']}] "
                f"{row['text']} :: {row['reason']}\n"
            )
    stream.write("\nOPAQUE IMPORTED BUT UNUSED ITEMS:\n")
    for row in rows:
        if row["decision"] == "OPAQUE_FIXED_UNUSED_NO_DEPENDENCY":
            stream.write(
                f"{row['source']}:{row['line']} {row['text']} :: {row['reason']}\n"
            )

print(f"assessed_items={len(rows)}")
print(f"assessment={OUT}")
print(f"summary={SUMMARY}")
