name = "klean-26-remove-duplicates"
version = "0.1.0"
defaultTargets = ["Klean26RemoveDuplicates"]
weakLeanArgs = [
    "-D maxHeartbeats=10000000"
]

buildDir = "/tmp/klean-generated-build"

[[lean_lib]]
name = "Klean26RemoveDuplicates"
