name = "klean-78-hex-key"
version = "0.1.0"
defaultTargets = ["Klean78HexKey"]
weakLeanArgs = [
    "-D maxHeartbeats=10000000"
]

buildDir = "/tmp/klean-generated-build"

[[lean_lib]]
name = "Klean78HexKey"
