name = "klean-11-string-xor"
version = "0.1.0"
defaultTargets = ["Klean11StringXor"]
weakLeanArgs = [
    "-D maxHeartbeats=10000000"
]

buildDir = "/tmp/klean-generated-build"

[[lean_lib]]
name = "Klean11StringXor"
