name = "klean-91-is-bored"
version = "0.1.0"
defaultTargets = ["Klean91IsBored"]
weakLeanArgs = [
    "-D maxHeartbeats=10000000"
]

buildDir = "/tmp/klean-generated-build"
moreLeanArgs = ["-D maxRecDepth=100000", "-s", "65536"]

[[lean_lib]]
name = "Klean91IsBored"
