name = "klean-60-sum-to-n"
version = "0.1.0"
defaultTargets = ["Klean60SumToN"]
weakLeanArgs = [
    "-D maxHeartbeats=10000000"
]

buildDir = "/tmp/klean-generated-build"
moreLeanArgs = ["-D maxRecDepth=100000", "-s", "65536"]

[[lean_lib]]
name = "Klean60SumToN"
