#!/usr/bin/env python3
"""Generate a complete textual inventory of K declarations and rules."""

from __future__ import annotations

import collections
import re
import sys
from pathlib import Path


START = re.compile(r"^  (configuration|syntax|context|rule|claim)\b")
ATTRS = (
    "function",
    "total",
    "functional",
    "symbol",
    "no-evaluators",
    "concrete",
    "priority",
    "simplification",
    "owise",
    "macro-rec",
    "macro",
    "strict",
    "seqstrict",
)


def blocks(path: Path):
    lines = path.read_text().splitlines()
    starts = [i for i, line in enumerate(lines) if START.match(line)]
    for position, begin in enumerate(starts):
        end = starts[position + 1] if position + 1 < len(starts) else len(lines)
        while end > begin and (
            not lines[end - 1].strip()
            or lines[end - 1].lstrip().startswith("//")
            or lines[end - 1].strip() == "endmodule"
        ):
            end -= 1
        kind = START.match(lines[begin]).group(1)
        text = "\n".join(lines[begin:end]).rstrip()
        yield begin + 1, kind, text


if len(sys.argv) < 2:
    raise SystemExit("usage: rule_inventory.py K_FILE [K_FILE ...]")

paths = [Path(arg) for arg in sys.argv[1:]]
counts: collections.Counter[str] = collections.Counter()
attribute_counts: collections.Counter[str] = collections.Counter()
records: list[tuple[Path, int, str, str, list[str]]] = []

for path in paths:
    for line_number, kind, text in blocks(path):
        counts[kind] += 1
        attrs = [attr for attr in ATTRS if re.search(rf"\b{re.escape(attr)}\b", text)]
        for attr in attrs:
            attribute_counts[attr] += 1
        records.append((path, line_number, kind, text, attrs))

print("# Exhaustive K source inventory")
print()
print("Generated by `rule_inventory.py` from the clean scratch source copies.")
print()
print(f"- Files: {len(paths)}")
print(f"- Inventory entries: {len(records)}")
for kind, count in sorted(counts.items()):
    print(f"- `{kind}` entries: {count}")
for attr, count in sorted(attribute_counts.items()):
    print(f"- Entries mentioning `{attr}`: {count}")

for path, line_number, kind, source, attrs in records:
    print()
    print(f"## {path}:{line_number} — {kind}")
    print()
    print("- Attributes:", ", ".join(f"`{attr}`" for attr in attrs) if attrs else "none")
    print("- Source:")
    print()
    print("```k")
    print(source)
    print("```")
