name = "klean-2-truncate-number"
version = "0.1.0"
defaultTargets = ["Klean2TruncateNumber"]
weakLeanArgs = [
    "-D maxHeartbeats=10000000"
]

buildDir = "/tmp/klean-generated-build"

[[lean_lib]]
name = "Klean2TruncateNumber"
