name = "klean-23-strlen"
version = "0.1.0"
defaultTargets = ["Klean23Strlen"]
weakLeanArgs = [
    "-D maxHeartbeats=10000000"
]

buildDir = "/tmp/klean-generated-build"

[[lean_lib]]
name = "Klean23Strlen"
