#!/usr/bin/env python3
"""Emit a source-located exhaustive inventory of top-level K declarations."""

from __future__ import annotations

import re
import sys
from pathlib import Path


START = re.compile(r"^  (configuration|syntax|context|rule|claim)\b")
STOP = re.compile(r"^  (configuration|syntax|context|rule|claim|endmodule)\b")


def entries(path: Path):
    lines = path.read_text(encoding="utf-8").splitlines()
    index = 0
    while index < len(lines):
        match = START.match(lines[index])
        if not match:
            index += 1
            continue
        start = index
        index += 1
        while index < len(lines) and not STOP.match(lines[index]):
            index += 1
        block = lines[start:index]
        normalized = " ".join(part.strip() for part in block if part.strip() and not part.lstrip().startswith("//"))
        attrs = sorted(set(re.findall(r"\b(functional|function|total|simplification|concrete|owise|priority\([^)]*\)|strict(?:\([^)]*\))?|seqstrict(?:\([^)]*\))?|macro)\b", normalized)))
        yield match.group(1), start + 1, index, normalized, attrs


paths = [Path(item) for item in sys.argv[1:]]
print("# Exhaustive K declaration and rule inventory")
print()
print("Generated by `inventory_k.py`; every top-level configuration, syntax, context, rule, and claim is source-located below.")
totals: dict[str, int] = {}
for path in paths:
    print()
    print(f"## {path}")
    print()
    number = 0
    for kind, start, end, normalized, attrs in entries(path):
        number += 1
        totals[kind] = totals.get(kind, 0) + 1
        attr_text = ", ".join(attrs) if attrs else "none"
        print(f"{number}. `{kind}` lines {start}-{end}; attributes: `{attr_text}`")
        print(f"   `{normalized.replace('`', chr(39))}`")
    if number == 0:
        print("(No top-level configuration, syntax, context, rule, or claim declarations.)")
print()
print("## Totals")
print()
for kind in sorted(totals):
    print(f"- {kind}: {totals[kind]}")
