name = "klean-92-any-int"
version = "0.1.0"
defaultTargets = ["Klean92AnyInt"]
weakLeanArgs = [
    "-D maxHeartbeats=10000000"
]

buildDir = "/tmp/klean-generated-build"

[[lean_lib]]
name = "Klean92AnyInt"
