name = "klean-75-is-multiply-prime"
version = "0.1.0"
defaultTargets = ["Klean75IsMultiplyPrime"]
weakLeanArgs = [
    "-D maxHeartbeats=10000000"
]

buildDir = "/tmp/klean-generated-build"

[[lean_lib]]
name = "Klean75IsMultiplyPrime"
