name = "klean-124-valid-date"
version = "0.1.0"
defaultTargets = ["Klean124ValidDate"]
weakLeanArgs = [
    "-D maxHeartbeats=10000000"
]

buildDir = "/tmp/klean-generated-build"

[[lean_lib]]
name = "Klean124ValidDate"
