name = "klean-37-sort-even"
version = "0.1.0"
defaultTargets = ["Klean37SortEven"]
weakLeanArgs = [
    "-D maxHeartbeats=10000000"
]

buildDir = "/tmp/klean-generated-build"

[[lean_lib]]
name = "Klean37SortEven"
