name = "klean-116-sort-array"
version = "0.1.0"
defaultTargets = ["Klean116SortArray"]
weakLeanArgs = [
    "-D maxHeartbeats=10000000"
]

buildDir = "/tmp/klean-generated-build"

[[lean_lib]]
name = "Klean116SortArray"
