#!/usr/bin/env python3
"""Exhaustive source-level inventory of supplied and proof-local K declarations."""

from __future__ import annotations

from collections import Counter, defaultdict
from pathlib import Path
import re


REFERENCE = Path("/reference/reference-semantics")
CANDIDATE = Path("/candidate")
paths = sorted([REFERENCE / "semantics.k", *(REFERENCE / "semantics").glob("*.k")])
paths += [CANDIDATE / "verification.k", CANDIDATE / "spec.k"]

start = re.compile(
    r"^\s*(configuration|syntax|rule|claim|context(?:\s+alias)?|macro|alias)\b"
)
stop = re.compile(
    r"^\s*(configuration|syntax|rule|claim|context(?:\s+alias)?|macro|alias|"
    r"module|endmodule|imports|requires)\b"
)
flag_names = (
    "function",
    "total",
    "functional",
    "macro",
    "opaque",
    "no-evaluators",
    "priority",
    "simplification",
    "anywhere",
    "owise",
    "strict",
    "seqstrict",
    "concrete",
    "symbol",
)


def source_scope(path: Path) -> str:
    if str(path).startswith(str(REFERENCE)):
        return "trusted-supplied-semantics"
    if path.name == "spec.k":
        return "candidate-claims"
    return "candidate-proof-local"


def disposition(path: Path, line: int, kind: str, block: str) -> str:
    if str(path).startswith(str(REFERENCE)):
        return "TRUSTED_BASELINE (candidate copy byte-identical)"
    if path.name == "spec.k":
        return "AUDITED_REACHABILITY_CLAIM"
    if kind == "syntax":
        return "AUDITED_DECLARATION"
    if 29 <= line <= 107:
        return "AUDITED_EXACT_AST_MACRO_EQUATION"
    if line >= 109:
        return "AUDITED_TOTAL_MATHEMATICAL_EQUATION"
    return "AUDITED_PROOF_LOCAL"


entries: list[dict[str, object]] = []
for path in paths:
    lines = path.read_text(encoding="utf-8").splitlines()
    index = 0
    while index < len(lines):
        match = start.match(lines[index])
        if not match:
            index += 1
            continue
        begin = index
        kind = match.group(1).replace(" ", "-")
        index += 1
        while index < len(lines) and not stop.match(lines[index]):
            index += 1
        block = "\n".join(lines[begin:index]).strip()
        code_only = "\n".join(line.split("//", 1)[0] for line in block.splitlines())
        flags = [
            flag
            for flag in flag_names
            if re.search(rf"\b{re.escape(flag)}\b", code_only)
        ]
        relative = (
            path.relative_to(REFERENCE).as_posix()
            if str(path).startswith(str(REFERENCE))
            else path.relative_to(CANDIDATE).as_posix()
        )
        entries.append(
            {
                "path": path,
                "relative": relative,
                "line": begin + 1,
                "kind": kind,
                "block": block,
                "flags": flags,
                "scope": source_scope(path),
                "disposition": disposition(path, begin + 1, kind, block),
            }
        )

print("# Exhaustive K declaration and rule inventory")
print()
print("Generated by `/audit-output/evidence/k_inventory.py` from every `.k` source")
print("in the trusted supplied-semantics tree plus candidate `verification.k` and `spec.k`.")
print()
print(f"Total inventoried declarations/rules: {len(entries)}")
print()

by_scope = Counter(str(entry["scope"]) for entry in entries)
by_kind = Counter(str(entry["kind"]) for entry in entries)
print("## Totals")
print()
for name, count in sorted(by_scope.items()):
    print(f"- scope `{name}`: {count}")
for name, count in sorted(by_kind.items()):
    print(f"- kind `{name}`: {count}")
for flag in flag_names:
    count = sum(flag in entry["flags"] for entry in entries)
    print(f"- flag `{flag}`: {count}")
print()

print("## Per-file counts")
print()
per_file: dict[str, Counter[str]] = defaultdict(Counter)
for entry in entries:
    per_file[str(entry["relative"])][str(entry["kind"])] += 1
for relative, counts in sorted(per_file.items()):
    rendered = ", ".join(f"{kind}={count}" for kind, count in sorted(counts.items()))
    print(f"- `{relative}`: {rendered}")
print()

print("## Entries")
print()
print("| ID | Scope | Kind | Flags | Disposition | Complete source declaration/rule |")
print("|---|---|---|---|---|---|")
for entry in entries:
    block = " ".join(str(entry["block"]).split())
    block = block.replace("|", r"\|")
    flags = ", ".join(entry["flags"]) or "none"
    identifier = f"{entry['relative']}:{entry['line']}"
    print(
        f"| `{identifier}` | {entry['scope']} | {entry['kind']} | {flags} | "
        f"{entry['disposition']} | `{block}` |"
    )
