name = "klean-102-choose-num"
version = "0.1.0"
defaultTargets = ["Klean102ChooseNum"]
weakLeanArgs = [
    "-D maxHeartbeats=10000000"
]

buildDir = "/tmp/klean-generated-build"

[[lean_lib]]
name = "Klean102ChooseNum"
