name = "klean-80-is-happy"
version = "0.1.0"
defaultTargets = ["Klean80IsHappy"]
weakLeanArgs = [
    "-D maxHeartbeats=10000000"
]

buildDir = "/tmp/klean-generated-build"

[[lean_lib]]
name = "Klean80IsHappy"
