name = "klean-49-modp"
version = "0.1.0"
defaultTargets = ["Klean49Modp"]
weakLeanArgs = [
    "-D maxHeartbeats=10000000"
]

buildDir = "/tmp/klean-generated-build"

[[lean_lib]]
name = "Klean49Modp"
