name = "klean-59-largest-prime-factor"
version = "0.1.0"
defaultTargets = ["Klean59LargestPrimeFactor"]
weakLeanArgs = [
    "-D maxHeartbeats=10000000"
]

buildDir = "/tmp/klean-generated-build"

[[lean_lib]]
name = "Klean59LargestPrimeFactor"
