#!/usr/bin/env python3
"""Emit an exhaustive declaration/rule inventory for the audited K sources."""

from __future__ import annotations

import hashlib
import re
from collections import Counter
from pathlib import Path

ROOT = Path("/tmp/audit-work/candidate-src")
SEM = ROOT / "reference-semantics"
FILES = [SEM / "semantics.k", *sorted((SEM / "semantics").glob("*.k"))]
FILES += [ROOT / "verification.k", ROOT / "spec.k"]

START = re.compile(r"^\s*(syntax|rule|claim|context|configuration)\b")
BOUNDARY = re.compile(
    r"^\s*(?:syntax|rule|claim|context|configuration|module|endmodule|imports|requires)\b"
)
MODULE = re.compile(r"^\s*module\s+([A-Za-z0-9_-]+)")

# Declarations/rules whose source-level behavior can be reached from solution.mpy.
# Strictness/context productions generated by K inherit reachability from their
# listed syntax declarations.
USED: dict[str, set[int]] = {
    "semantics/syntax.k": {
        9, 12, 15, 22, 28, 38, 39, 41, 50, 53, 56, 57, 60, 61
    },
    "semantics/core.k": {
        13, 15, 25, 31, 33, 39, 49, 124, 125, 126, 127, 130, 131, 132,
        152, 157, 158, 185, 186, 189, 190, 191, 194, 209
    },
    "semantics/int.k": {9, 15, 16, 19, 20},
    "semantics/operators.k": {12},
    "semantics/controls.k": {9},
    "semantics/functions.k": {8, 14, 63, 64, 78, 80, 85},
    "semantics/call.k": {19, 20, 21, 31, 69},
    "semantics/builtins.k": {17, 108, 111, 114, 115, 116, 117, 118, 119},
    "semantics/subscript.k": {
        27, 28, 44, 49, 50, 51, 52, 54, 55, 56, 61, 63, 68, 72, 73,
        74, 76, 77, 79, 81, 83, 84, 86, 88, 90, 91, 93, 96, 97, 99,
        102, 103, 105, 116, 117, 120
    },
}


def relative(path: Path) -> str:
    if path == ROOT / "verification.k":
        return "verification.k"
    if path == ROOT / "spec.k":
        return "spec.k"
    return str(path.relative_to(SEM))


def clean_statement(lines: list[str]) -> str:
    kept: list[str] = []
    for line in lines:
        stripped = line.strip()
        if not stripped or stripped.startswith("//"):
            continue
        kept.append(stripped)
    return " ".join(kept)


def classify(kind: str, text: str) -> str:
    tags: list[str] = []
    if kind == "syntax":
        tags.append("syntax")
        for attr in (
            "function",
            "total",
            "functional",
            "symbol",
            "no-evaluators",
            "macro",
            "strict",
            "seqstrict",
        ):
            if re.search(rf"\b{re.escape(attr)}\b", text):
                tags.append(attr)
        if "no-evaluators" in text:
            tags.append("opaque")
    elif kind == "rule":
        tags.append("operational" if "<k>" in text else "equational")
        for attr in (
            "priority",
            "simplification",
            "concrete",
            "owise",
            "anywhere",
            "macro",
        ):
            if re.search(rf"\b{re.escape(attr)}\b", text):
                tags.append(attr)
    else:
        tags.append(kind)
    return ", ".join(tags)


records: list[dict[str, object]] = []
for path in FILES:
    lines = path.read_text().splitlines()
    module = "(outside module)"
    i = 0
    while i < len(lines):
        module_match = MODULE.match(lines[i])
        if module_match:
            module = module_match.group(1)
        match = START.match(lines[i])
        if not match:
            i += 1
            continue
        start = i
        i += 1
        while i < len(lines) and not BOUNDARY.match(lines[i]):
            i += 1
        kind = match.group(1)
        text = clean_statement(lines[start:i])
        rel = relative(path)
        line = start + 1
        if rel in ("verification.k", "spec.k"):
            decision = "candidate-local; individually decided in 05_static_review.md"
        elif line in USED.get(rel, set()):
            decision = "fixed supplied semantics; reachable and path-reviewed"
        else:
            decision = "fixed supplied semantics; not reached by submitted AST"
        records.append(
            {
                "source": rel,
                "line": line,
                "module": module,
                "kind": kind,
                "class": classify(kind, text),
                "decision": decision,
                "text": text,
            }
        )

kind_counts = Counter(str(r["kind"]) for r in records)
class_counts = Counter(
    tag.strip()
    for record in records
    for tag in str(record["class"]).split(",")
)

print("# Exhaustive K declaration and rule inventory")
print()
print("Generated by `evidence/05_inventory.py` from the scratch source copy.")
print(
    "Each row is a top-level syntax declaration, rule, claim, context, or "
    "configuration. Multi-line declarations are normalized into one row."
)
print()
print(f"- Total records: {len(records)}")
print(f"- Kind counts: {dict(sorted(kind_counts.items()))}")
print(f"- Class/tag counts: {dict(sorted(class_counts.items()))}")
print()
print("## Source hashes")
print()
for path in FILES:
    digest = hashlib.sha256(path.read_bytes()).hexdigest()
    print(f"- `{relative(path)}`: `{digest}`")
print()
print("## Inventory")
print()
print("| # | Source | Module | Kind/class | Review decision | Declaration/rule |")
print("|---:|---|---|---|---|---|")
for number, record in enumerate(records, 1):
    text = str(record["text"]).replace("|", r"\|")
    decision = str(record["decision"]).replace("|", r"\|")
    print(
        f"| {number} | `{record['source']}:{record['line']}` | "
        f"`{record['module']}` | {record['class']} | {decision} | "
        f"`{text}` |"
    )
