#!/usr/bin/env python3
"""Emit a source-location inventory of all K declarations and rules in scope."""

from __future__ import annotations

from collections import Counter
from pathlib import Path
import re


SEMANTICS_ROOT = Path("/reference/reference-semantics")
FILES = [SEMANTICS_ROOT / "semantics.k"]
FILES += sorted((SEMANTICS_ROOT / "semantics").glob("*.k"))
FILES += [Path("/candidate/verification.k"), Path("/candidate/spec.k")]

START = re.compile(
    r"^\s*(requires|module|endmodule|imports|configuration|syntax|context|"
    r"rule|claim|alias)\b"
)
ATTRIBUTE_WORDS = [
    "function",
    "functional",
    "total",
    "macro",
    "symbol",
    "no-evaluators",
    "concrete",
    "simplification",
    "symbolic",
    "preserves-definedness",
    "priority",
    "owise",
    "strict",
    "seqstrict",
]


def source_role(path: Path) -> str:
    if path == Path("/candidate/verification.k"):
        return "proof-extension"
    if path == Path("/candidate/spec.k"):
        return "reachability-claims"
    if path.name == "concrete.k":
        return "supplied-runtime-only"
    return "supplied-fixed-semantics"


def extract(path: Path) -> list[tuple[int, str, str]]:
    lines = path.read_text().splitlines()
    starts: list[tuple[int, str]] = []
    for index, line in enumerate(lines):
        match = START.match(line)
        if match:
            starts.append((index, match.group(1)))
    records = []
    for ordinal, (index, kind) in enumerate(starts):
        next_index = starts[ordinal + 1][0] if ordinal + 1 < len(starts) else len(lines)
        block_lines = lines[index:next_index]
        while block_lines and (
            not block_lines[-1].strip() or block_lines[-1].lstrip().startswith("//")
        ):
            block_lines.pop()
        raw = "\n".join(block_lines).strip()
        records.append((index + 1, kind, raw))
    return records


def one_line(raw: str) -> str:
    text = " ".join(
        line.strip() for line in raw.splitlines() if not line.lstrip().startswith("//")
    )
    return re.sub(r"\s+", " ", text)


def attributes(raw: str) -> str:
    found = []
    for word in ATTRIBUTE_WORDS:
        if re.search(rf"\b{re.escape(word)}\b", raw):
            found.append(word)
    return ", ".join(found) if found else "—"


def main() -> None:
    counts: Counter[str] = Counter()
    role_counts: Counter[str] = Counter()
    records_by_file = {}
    for path in FILES:
        records = extract(path)
        records_by_file[path] = records
        for _line, kind, _raw in records:
            counts[kind] += 1
            role_counts[source_role(path)] += 1

    print("# Exhaustive K source inventory")
    print()
    print(
        "Generated by the independent reviewer from the trusted supplied "
        "semantics and the candidate proof sources. Every top-level `requires`, "
        "`module`, `imports`, `configuration`, `syntax`, `context`, `rule`, "
        "and `claim` start is listed with its complete source block collapsed "
        "to one line. `endmodule` markers are counted but omitted from the "
        "tables as structural delimiters."
    )
    print()
    print(f"- Files: {len(FILES)}")
    print(f"- Inventory records: {sum(counts.values())}")
    print(
        "- Counts: "
        + ", ".join(f"{kind}={count}" for kind, count in sorted(counts.items()))
    )
    print(
        "- Source roles: "
        + ", ".join(f"{role}={count}" for role, count in sorted(role_counts.items()))
    )

    global_id = 0
    for path in FILES:
        print()
        print(f"## `{path}`")
        print()
        print(f"Role: `{source_role(path)}`")
        print()
        print("| ID | Line | Kind | Attributes | Complete declaration/rule block |")
        print("|---:|---:|---|---|---|")
        for line, kind, raw in records_by_file[path]:
            if kind == "endmodule":
                continue
            global_id += 1
            display = one_line(raw).replace("|", "&#124;")
            display = display.replace("`", "&#96;")
            print(
                f"| K{global_id:04d} | {line} | `{kind}` | "
                f"{attributes(raw)} | `{display}` |"
            )


if __name__ == "__main__":
    main()
