name = "klean-152-compare"
version = "0.1.0"
defaultTargets = ["Klean152Compare"]
weakLeanArgs = [
    "-D maxHeartbeats=10000000"
]

buildDir = "/tmp/klean-generated-build"

[[lean_lib]]
name = "Klean152Compare"
