name = "klean-140-fix-spaces"
version = "0.1.0"
defaultTargets = ["Klean140FixSpaces"]
weakLeanArgs = [
    "-D maxHeartbeats=10000000"
]

buildDir = "/tmp/klean-generated-build"
moreLeanArgs = ["-D maxRecDepth=100000", "-s", "65536"]

[[lean_lib]]
name = "Klean140FixSpaces"
