#!/usr/bin/env python3
"""Generate K equations for CPython's per-code-point str.swapcase mapping."""

from pathlib import Path
import platform
import unicodedata


def k_string(value: str) -> str:
    pieces = []
    # K 7.1 documents incomplete code-point support in its String backends.
    # The frontend nevertheless stores UTF-8 input losslessly as bytes, so the
    # semantics uses escaped UTF-8 on both sides of each mapping equation.
    for byte in value.encode("utf-8"):
        if 0x20 <= byte <= 0x7E and byte not in (ord('"'), ord("\\")):
            pieces.append(chr(byte))
        elif byte == ord('"'):
            pieces.append(r'\"')
        elif byte == ord("\\"):
            pieces.append(r"\\")
        else:
            pieces.append(f"\\x{byte:02x}")
    return '"' + "".join(pieces) + '"'


lines = [
    "// Generated by gen_unicode_case.py; do not edit by hand.",
    f"// Python {platform.python_version()}, Unicode {unicodedata.unidata_version}.",
    "module PYTHON-UNICODE-CASE",
    "  imports STRING",
    "",
    "  syntax String ::= pySwapChar(String) [function, total]",
]

for codepoint in range(0x110000):
    character = chr(codepoint)
    swapped = character.swapcase()
    if swapped != character:
        lines.append(
            f"  rule pySwapChar({k_string(character)}) => {k_string(swapped)}"
        )

lines.extend(
    [
        "  rule pySwapChar(C) => C [owise]",
        "endmodule",
        "",
    ]
)

Path("unicode-case.k").write_text("\n".join(lines), encoding="utf-8")
