name = "klean-4-mean-absolute-deviation"
version = "0.1.0"
defaultTargets = ["Klean4MeanAbsoluteDeviation"]
weakLeanArgs = [
    "-D maxHeartbeats=10000000"
]

buildDir = "/tmp/klean-generated-build"
moreLeanArgs = ["-D maxRecDepth=100000", "-s", "65536"]

[[lean_lib]]
name = "Klean4MeanAbsoluteDeviation"
