#!/usr/bin/env python3
"""Emit an exhaustive declaration/rule inventory for the audited K sources."""

from __future__ import annotations

import collections
import re
from pathlib import Path


TRUSTED_ROOT = Path("/reference/reference-semantics")
CANDIDATE_ROOT = Path("/candidate")
START = re.compile(r"^\s*(configuration|syntax|context|rule|claim|alias)\b")


def source_files() -> list[tuple[str, Path, str]]:
    result: list[tuple[str, Path, str]] = []
    for path in sorted(TRUSTED_ROOT.rglob("*.k")):
        result.append(
            (
                f"reference-semantics/{path.relative_to(TRUSTED_ROOT).as_posix()}",
                path,
                "fixed-supplied",
            )
        )
    for name in (
        "projection.k",
        "verification.k",
        "connection-definition.k",
        "connection-spec.k",
        "spec.k",
    ):
        result.append((name, CANDIDATE_ROOT / name, "candidate-proof"))
    return result


def entries(path: Path):
    lines = path.read_text(encoding="utf-8").splitlines()
    starts: list[tuple[int, str]] = []
    for index, line in enumerate(lines):
        match = START.match(line)
        if match:
            starts.append((index, match.group(1)))
    for position, (start, kind) in enumerate(starts):
        stop = starts[position + 1][0] if position + 1 < len(starts) else len(lines)
        block_lines = lines[start:stop]
        while block_lines and (
            not block_lines[-1].strip()
            or block_lines[-1].lstrip().startswith("//")
            or block_lines[-1].strip() in {"endmodule"}
        ):
            block_lines.pop()
        text = " ".join(line.strip() for line in block_lines if line.strip())
        yield start + 1, start + len(block_lines), kind, text


def flags(text: str) -> str:
    found: list[str] = []
    for attribute in (
        "function",
        "total",
        "functional",
        "simplification",
        "priority",
        "owise",
        "macro-rec",
        "macro",
        "concrete",
        "anywhere",
        "symbol",
        "no-evaluators",
        "strict",
        "seqstrict",
        "hook",
    ):
        if re.search(rf"\b{re.escape(attribute)}\b", text):
            found.append(attribute)
    if "no-evaluators" in found or (
        "symbol" in found and "concrete" not in found
    ):
        found.append("opaque-or-proof-abstract")
    return ", ".join(found) if found else "ordinary"


def escape(text: str) -> str:
    return text.replace("|", r"\|").replace("`", "'")


def main() -> None:
    records: list[tuple[str, str, int, int, str, str, str]] = []
    kind_counts: collections.Counter[str] = collections.Counter()
    origin_counts: collections.Counter[str] = collections.Counter()
    flag_counts: collections.Counter[str] = collections.Counter()
    for display, path, origin in source_files():
        for start, stop, kind, text in entries(path):
            record_flags = flags(text)
            records.append(
                (origin, display, start, stop, kind, record_flags, text)
            )
            kind_counts[kind] += 1
            origin_counts[origin] += 1
            for flag in record_flags.split(", "):
                flag_counts[flag] += 1

    print("# Exhaustive K source inventory")
    print()
    print(
        "Generated by `python3 /audit-output/evidence/05_rule_inventory.py` "
        "from the mounted supplied semantics and candidate proof sources."
    )
    print()
    print(f"- Total inventoried declarations/rules/claims: {len(records)}")
    print(f"- By origin: {dict(sorted(origin_counts.items()))}")
    print(f"- By kind: {dict(sorted(kind_counts.items()))}")
    print(f"- Attribute/role counts: {dict(sorted(flag_counts.items()))}")
    print()
    print(
        "| ID | Origin | File | Lines | Kind | Attributes / role | "
        "Complete logical source block |"
    )
    print("|---:|---|---|---:|---|---|---|")
    for index, (origin, display, start, stop, kind, record_flags, text) in enumerate(
        records, 1
    ):
        line_span = str(start) if start == stop else f"{start}-{stop}"
        print(
            f"| {index} | {origin} | `{display}` | {line_span} | {kind} | "
            f"{escape(record_flags)} | {escape(text)} |"
        )


if __name__ == "__main__":
    main()
