name = "klean-28-concatenate"
version = "0.1.0"
defaultTargets = ["Klean28Concatenate"]
weakLeanArgs = [
    "-D maxHeartbeats=10000000"
]

buildDir = "/tmp/klean-generated-build"

[[lean_lib]]
name = "Klean28Concatenate"
