#!/usr/bin/env python3
"""Emit an exhaustive declaration/rule inventory for the audited K sources."""

from __future__ import annotations

import collections
import re
from pathlib import Path


ROOT = Path("/tmp/audit-work/129-minPath")
FILES = [
    ROOT / "reference-semantics/semantics.k",
    *sorted((ROOT / "reference-semantics/semantics").glob("*.k")),
    ROOT / "verification.k",
    ROOT / "spec.k",
]
START = re.compile(r"^\s*(configuration|syntax|context|rule|claim)\b")
STOP = re.compile(r"^\s*(configuration|syntax|context|rule|claim|module|endmodule|requires|imports)\b")


def classify(source: Path, kind: str, block: str) -> list[str]:
    tags = []
    if "reference-semantics" in str(source):
        tags.append("SUPPLIED_FIXED")
    elif source.name == "verification.k":
        tags.append("PROOF_LOCAL")
    else:
        tags.append("CLAIM_SPEC")
    tags.append(kind.upper())
    for attr, tag in (
        ("function", "FUNCTION"),
        ("functional", "FUNCTIONAL"),
        ("total", "TOTAL"),
        ("symbol(", "SYMBOL"),
        ("no-evaluators", "OPAQUE"),
        ("priority(", "PRIORITY"),
        ("simplification", "SIMPLIFICATION"),
        ("concrete", "CONCRETE"),
        ("macro-rec", "MACRO_REC"),
        ("macro", "MACRO"),
        ("owise", "OWISE"),
        ("strict", "STRICT"),
        ("seqstrict", "SEQSTRICT"),
    ):
        if attr in block:
            tags.append(tag)
    return tags


records = []
for path in FILES:
    lines = path.read_text().splitlines()
    i = 0
    while i < len(lines):
        match = START.match(lines[i])
        if not match:
            i += 1
            continue
        kind = match.group(1)
        start = i
        i += 1
        while i < len(lines) and not STOP.match(lines[i]):
            i += 1
        block = "\n".join(lines[start:i]).rstrip()
        records.append(
            {
                "file": str(path.relative_to(ROOT)),
                "start": start + 1,
                "end": i,
                "kind": kind,
                "tags": classify(path, kind, block),
                "block": block,
            }
        )

by_file = collections.Counter(record["file"] for record in records)
by_kind = collections.Counter(record["kind"] for record in records)
by_tag = collections.Counter(tag for record in records for tag in record["tags"])

print("# Exhaustive K declaration and rule inventory")
print()
print("Generated by `evidence/k_inventory.py` from the fresh scratch source copy.")
print("Each `syntax`, `configuration`, `context`, `rule`, and `claim` block is listed once.")
print()
print(f"Total inventoried blocks: {len(records)}")
print()
print("## Counts by kind")
print()
for key, value in sorted(by_kind.items()):
    print(f"- `{key}`: {value}")
print()
print("## Counts by classification tag")
print()
for key, value in sorted(by_tag.items()):
    print(f"- `{key}`: {value}")
print()
print("## Counts by file")
print()
for key, value in sorted(by_file.items()):
    print(f"- `{key}`: {value}")
print()
print("## Complete inventory")
for index, record in enumerate(records, 1):
    loc = f"{record['file']}:{record['start']}"
    if record["end"] > record["start"]:
        loc += f"-{record['end']}"
    print()
    print(f"### K-{index:04d} — `{loc}`")
    print()
    print("Tags: " + ", ".join(f"`{tag}`" for tag in record["tags"]))
    print()
    print("```k")
    print(record["block"])
    print("```")
