name = "klean-58-common"
version = "0.1.0"
defaultTargets = ["Klean58Common"]
weakLeanArgs = [
    "-D maxHeartbeats=10000000"
]

buildDir = "/tmp/klean-generated-build"
moreLeanArgs = ["-D maxRecDepth=100000", "-s", "65536"]

[[lean_lib]]
name = "Klean58Common"
