#!/usr/bin/env python3
"""Produce a complete line-addressed inventory of K declarations and rules."""

from __future__ import annotations

import argparse
import re
from collections import Counter
from pathlib import Path


START = re.compile(
    r"^\s*(module|imports|configuration|syntax|context(?:\s+alias)?|"
    r"rule|claim|priority)\b"
)
ATTRS = (
    "function",
    "total",
    "functional",
    "macro",
    "macro-rec",
    "simplification",
    "priority",
    "owise",
    "concrete",
    "anywhere",
    "symbol",
    "strict",
    "seqstrict",
)


def entries(path: Path):
    lines = path.read_text(encoding="utf-8").splitlines()
    starts = []
    for index, line in enumerate(lines):
        match = START.match(line)
        if match:
            starts.append((index, match.group(1)))
    for pos, (index, kind) in enumerate(starts):
        end = starts[pos + 1][0] if pos + 1 < len(starts) else len(lines)
        for probe in range(index + 1, end):
            if lines[probe].strip() == "endmodule":
                end = probe
                break
        block = "\n".join(lines[index:end]).rstrip()
        yield index + 1, kind, block


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, required=True)
    parser.add_argument("--verification", type=Path, required=True)
    parser.add_argument("--spec", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()

    files = sorted(args.root.rglob("*.k")) + [args.verification, args.spec]
    records = []
    kind_counts: Counter[str] = Counter()
    attr_counts: Counter[str] = Counter()
    file_counts: Counter[str] = Counter()
    file_kind_counts: dict[str, Counter[str]] = {}

    for path in files:
        for line, kind, block in entries(path):
            attrs = [attr for attr in ATTRS if re.search(rf"\b{re.escape(attr)}\b", block)]
            records.append((path, line, kind, attrs, block))
            kind_counts[kind] += 1
            file_counts[str(path)] += 1
            file_kind_counts.setdefault(str(path), Counter())[kind] += 1
            attr_counts.update(attrs)

    with args.output.open("w", encoding="utf-8") as out:
        out.write("# Exhaustive K source inventory\n\n")
        out.write(
            "Generated by `evidence/scripts/inventory_k.py` from the fresh scratch "
            "source copies. Each source construct beginning with `module`, `imports`, "
            "`configuration`, `syntax`, `context`, `rule`, `claim`, or `priority` is "
            "listed with its complete line-oriented block.\n\n"
        )
        out.write(f"Total entries: {len(records)}\n\n")
        out.write("Kind counts: " + ", ".join(f"{k}={v}" for k, v in sorted(kind_counts.items())) + "\n\n")
        out.write("Attribute counts: " + ", ".join(f"{k}={v}" for k, v in sorted(attr_counts.items())) + "\n\n")
        out.write("File counts:\n\n")
        for name, count in sorted(file_counts.items()):
            breakdown = ", ".join(
                f"{kind}={value}" for kind, value in sorted(file_kind_counts[name].items())
            )
            out.write(f"- `{name}`: {count} ({breakdown})\n")
        out.write("\n")

        for number, (path, line, kind, attrs, block) in enumerate(records, 1):
            attr_text = ", ".join(attrs) if attrs else "none detected"
            out.write(
                f"## {number}. `{path}:{line}` — {kind}\n\n"
                f"Attributes/classifiers: {attr_text}\n\n"
                "```k\n"
                f"{block}\n"
                "```\n\n"
            )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
