name = "klean-133-sum-squares"
version = "0.1.0"
defaultTargets = ["Klean133SumSquares"]
weakLeanArgs = [
    "-D maxHeartbeats=10000000"
]

buildDir = "/tmp/klean-generated-build"

[[lean_lib]]
name = "Klean133SumSquares"
