name = "klean-33-sort-third"
version = "0.1.0"
defaultTargets = ["Klean33SortThird"]
weakLeanArgs = [
    "-D maxHeartbeats=10000000"
]

buildDir = "/tmp/klean-generated-build"

[[lean_lib]]
name = "Klean33SortThird"
