default: null
specializations:
- - Lbl'UndsSClnUndsUnds'MPY'Unds'Ints'Unds'Int'Unds'Ints{}
  - action:
    - 716
    - - - &id001 ['1']
        - INT.Int
      - - ['1', '2']
        - STRING.String
      - - ['0', '2']
        - INT.Int
  - [INT.Int, STRING.String]
- - Lbl'Stop'Ints'Unds'MPY'Unds'Ints{}
  - action:
    - 717
    - - - *id001
        - INT.Int
  - []
sort: STRING.String
occurrence: ['2']
