default: null
specializations:
- - Lbl'-LT-'generatedTop'-GT-'{}
  - default: null
    specializations:
    - - Lbl'-LT-'mpy'-GT-'{}
      - default: null
        specializations:
        - - Lbl'-LT-'funs'-GT-'{}
          - default: null
            specializations:
            - - Lbl'-LT-'k'-GT-'{}
              - default: fail
                specializations:
                - - kseq{}
                  - default: fail
                    specializations:
                    - - Lblinvoke2'LParUndsCommUndsCommUndsRParUnds'MPY'Unds'KItem'Unds'String'Unds'PyVal'Unds'PyVal{}
                      - next:
                          args:
                          - - &id001 ['0', '1', '0', '1']
                            - MAP.Map
                          - - &id002 [size, '0', '1', '0', '1']
                            - STRING.String
                          next:
                            args:
                            - - *id001
                              - MAP.Map
                            - - *id002
                              - STRING.String
                            next:
                              default: null
                              specializations:
                              - - '1'
                                - default: fail
                                  specializations:
                                  - - inj{SortFun{}, SortKItem{}}
                                    - default: null
                                      specializations:
                                      - - Lblfunction'LParUndsCommUndsRParUnds'MPY'Unds'Fun'Unds'Params'Unds'Stmts{}
                                        - default: null
                                          specializations:
                                          - - LblParams'LParUndsRParUnds'MPY-SYNTAX'Unds'Params'Unds'Ids{}
                                            - default: fail
                                              specializations:
                                              - - Lbl'UndsCommUndsUnds'MPY-SYNTAX'Unds'Ids'Unds'String'Unds'Ids{}
                                                - default: fail
                                                  specializations:
                                                  - - Lbl'UndsCommUndsUnds'MPY-SYNTAX'Unds'Ids'Unds'String'Unds'Ids{}
                                                    - default: fail
                                                      specializations:
                                                      - - Lbl'Stop'List'LBraQuotUndsCommUndsUnds'MPY-SYNTAX'Unds'Ids'Unds'String'Unds'Ids'QuotRBraUnds'Ids{}
                                                        - action:
                                                          - 576
                                                          - - - ['1', '1']
                                                              - STRING.String
                                                            - - ['1', '0', '0', '0',
                                                                '1']
                                                              - STRING.String
                                                            - - ['SymbolP(inj{SortString{},
                                                                  SortKItem{}},List(VariableP(Some(Num(0,Num(0,Num(0,Num(0,Num(0,Num(1,Base()))))))),StringS())))_rem',
                                                                '0', '1', '0', '1']
                                                              - MAP.Map
                                                            - - ['2', '0', '1']
                                                              - STRING.String
                                                            - - ['3', '0', '1']
                                                              - STRING.String
                                                            - - ['4', '0', '1']
                                                              - STRING.String
                                                            - - ['1', '0', '1']
                                                              - STRING.String
                                                            - - ['1', '0', 'SymbolP(inj{SortString{},
                                                                  SortKItem{}},List(VariableP(Some(Num(0,Num(0,Num(0,Num(0,Num(0,Num(1,Base()))))))),StringS())))_val',
                                                                '0', '1', '0', '1']
                                                              - STRING.String
                                                            - - &id003 ['0', '0',
                                                                '0', '0', '0', '1']
                                                              - STRING.String
                                                            - - ['1', '0', '0', '0',
                                                                '0', '1']
                                                              - STRING.String
                                                            - - ['2', '0', '0', '0',
                                                                '0', '1']
                                                              - STRING.String
                                                            - - ['0', '0', '0', '0',
                                                                'SymbolP(inj{SortString{},
                                                                  SortKItem{}},List(VariableP(Some(Num(0,Num(0,Num(0,Num(0,Num(0,Num(1,Base()))))))),StringS())))_val',
                                                                '0', '1', '0', '1']
                                                              - STRING.String
                                                            - - ['0', '1', '0', '0',
                                                                '0', 'SymbolP(inj{SortString{},
                                                                  SortKItem{}},List(VariableP(Some(Num(0,Num(0,Num(0,Num(0,Num(0,Num(1,Base()))))))),StringS())))_val',
                                                                '0', '1', '0', '1']
                                                              - STRING.String
                                                        - []
                                                      sort: STRING.String
                                                      occurrence: ['1', '1', '0',
                                                        '0', '0', 'SymbolP(inj{SortString{},
                                                          SortKItem{}},List(VariableP(Some(Num(0,Num(0,Num(0,Num(0,Num(0,Num(1,Base()))))))),StringS())))_val',
                                                        '0', '1', '0', '1']
                                                    - [STRING.String, STRING.String]
                                                  sort: STRING.String
                                                  occurrence: ['1', '0', '0', '0',
                                                    'SymbolP(inj{SortString{}, SortKItem{}},List(VariableP(Some(Num(0,Num(0,Num(0,Num(0,Num(0,Num(1,Base()))))))),StringS())))_val',
                                                    '0', '1', '0', '1']
                                                - [STRING.String, STRING.String]
                                              sort: STRING.String
                                              occurrence: ['0', '0', '0', 'SymbolP(inj{SortString{},
                                                  SortKItem{}},List(VariableP(Some(Num(0,Num(0,Num(0,Num(0,Num(0,Num(1,Base()))))))),StringS())))_val',
                                                '0', '1', '0', '1']
                                            - [STRING.String]
                                          sort: STRING.String
                                          occurrence: ['0', '0', 'SymbolP(inj{SortString{},
                                              SortKItem{}},List(VariableP(Some(Num(0,Num(0,Num(0,Num(0,Num(0,Num(1,Base()))))))),StringS())))_val',
                                            '0', '1', '0', '1']
                                        - [STRING.String, STRING.String]
                                      sort: STRING.String
                                      occurrence: ['0', 'SymbolP(inj{SortString{},
                                          SortKItem{}},List(VariableP(Some(Num(0,Num(0,Num(0,Num(0,Num(0,Num(1,Base()))))))),StringS())))_val',
                                        '0', '1', '0', '1']
                                    - [STRING.String]
                                  sort: STRING.String
                                  occurrence: ['SymbolP(inj{SortString{}, SortKItem{}},List(VariableP(Some(Num(0,Num(0,Num(0,Num(0,Num(0,Num(1,Base()))))))),StringS())))_val',
                                    '0', '1', '0', '1']
                                - [STRING.String, MAP.Map, MAP.Map]
                              - - '0'
                                - fail
                                - [MAP.Map]
                              isnull: true
                              sort: STRING.String
                              occurrence: ['SymbolP(inj{SortString{}, SortKItem{}},List(VariableP(Some(Num(0,Num(0,Num(0,Num(0,Num(0,Num(1,Base()))))))),StringS())))_val',
                                '0', '1', '0', '1']
                            function: hook_MAP_remove
                            sort: MAP.Map
                            occurrence: ['SymbolP(inj{SortString{}, SortKItem{}},List(VariableP(Some(Num(0,Num(0,Num(0,Num(0,Num(0,Num(1,Base()))))))),StringS())))_rem',
                              '0', '1', '0', '1']
                          function: hook_MAP_lookup_null
                          sort: STRING.String
                          occurrence: ['SymbolP(inj{SortString{}, SortKItem{}},List(VariableP(Some(Num(0,Num(0,Num(0,Num(0,Num(0,Num(1,Base()))))))),StringS())))_val',
                            '0', '1', '0', '1']
                        pattern:
                          args:
                          - hook: STRING.String
                            occurrence: *id003
                          constructor: inj{SortString{}, SortKItem{}}
                        occurrence: *id002
                        sort: STRING.String
                      - [STRING.String, STRING.String, STRING.String]
                    sort: STRING.String
                    occurrence: ['0', '0', '0', '0', '1']
                  - [STRING.String, STRING.String]
                sort: STRING.String
                occurrence: ['0', '0', '0', '1']
              - [STRING.String]
            sort: STRING.String
            occurrence: ['0', '0', '1']
          - [MAP.Map]
        sort: STRING.String
        occurrence: ['1', '0', '1']
      - [STRING.String, STRING.String, STRING.String, STRING.String, STRING.String]
    sort: STRING.String
    occurrence: ['0', '1']
  - [STRING.String, STRING.String]
sort: STRING.String
occurrence: ['1']
