default: null
specializations:
- - Lbl'-LT-'generatedTop'-GT-'{}
  - default: null
    specializations:
    - - Lbl'-LT-'mpy'-GT-'{}
      - default: null
        specializations:
        - - Lbl'-LT-'k'-GT-'{}
          - default: fail
            specializations:
            - - kseq{}
              - default: fail
                specializations:
                - - inj{SortPyVal{}, SortKItem{}}
                  - default: fail
                    specializations:
                    - - LblVInt'LParUndsRParUnds'MPY'Unds'PyVal'Unds'Int{}
                      - default: fail
                        specializations:
                        - - kseq{}
                          - default: fail
                            specializations:
                            - - LblbinRightK'LParUndsCommUndsRParUnds'MPY'Unds'KItem'Unds'String'Unds'PyVal{}
                              - next:
                                  args:
                                  - - &id001 ['0', '0', '1', '0', '0', '0', '1']
                                    - STRING.String
                                  - - &id003 [lit, '-', STRING.String]
                                    - STRING.String
                                  next:
                                    default: null
                                    specializations:
                                    - - '1'
                                      - default:
                                          default: fail
                                          specializations:
                                          - - LblVInt'LParUndsRParUnds'MPY'Unds'PyVal'Unds'Int{}
                                            - action:
                                              - 569
                                              - - - ['1', '1']
                                                  - STRING.String
                                                - - ['1', '1', '0', '0', '0', '1']
                                                  - STRING.String
                                                - - ['1', '0', '1']
                                                  - STRING.String
                                                - - ['2', '0', '1']
                                                  - STRING.String
                                                - - ['3', '0', '1']
                                                  - STRING.String
                                                - - ['4', '0', '1']
                                                  - STRING.String
                                                - - ['0', '1', '0', '1', '0', '0',
                                                    '0', '1']
                                                  - INT.Int
                                                - - ['0', '0', '0', '0', '0', '0',
                                                    '1']
                                                  - INT.Int
                                            - [INT.Int]
                                          sort: STRING.String
                                          occurrence: ['1', '0', '1', '0', '0', '0',
                                            '1']
                                        specializations: []
                                        sort: STRING.String
                                        occurrence: *id001
                                      - []
                                    - - '0'
                                      - default: fail
                                        specializations: []
                                        sort: STRING.String
                                        occurrence: ['0', '0', '1', '0', '0', '0',
                                          '1']
                                      - []
                                    bitwidth: 1
                                    sort: BOOL.Bool
                                    occurrence: &id002 [eq, '0', '0', '1', '0', '0',
                                      '0', '1', and, lit, '-', STRING.String]
                                  function: hook_KEQUAL_eq
                                  sort: BOOL.Bool
                                  occurrence: *id002
                                pattern: {hook: STRING.String, literal: '-'}
                                occurrence: *id003
                                sort: STRING.String
                              - [STRING.String, STRING.String]
                            sort: STRING.String
                            occurrence: ['0', '1', '0', '0', '0', '1']
                          - [STRING.String, STRING.String]
                        sort: STRING.String
                        occurrence: ['1', '0', '0', '0', '1']
                      - [INT.Int]
                    sort: STRING.String
                    occurrence: ['0', '0', '0', '0', '0', '1']
                  - [STRING.String]
                sort: STRING.String
                occurrence: ['0', '0', '0', '0', '1']
              - [STRING.String, STRING.String]
            sort: STRING.String
            occurrence: ['0', '0', '0', '1']
          - [STRING.String]
        sort: STRING.String
        occurrence: ['0', '0', '1']
      - [STRING.String, STRING.String, STRING.String, STRING.String, STRING.String]
    sort: STRING.String
    occurrence: ['0', '1']
  - [STRING.String, STRING.String]
sort: STRING.String
occurrence: ['1']
