default: null
specializations:
- - Lbl'-LT-'generatedTop'-GT-'{}
  - default: null
    specializations:
    - - Lbl'-LT-'mpy'-GT-'{}
      - default: null
        specializations:
        - - Lbl'-LT-'k'-GT-'{}
          - default: fail
            specializations:
            - - kseq{}
              - default: fail
                specializations:
                - - Lbleval'LParUndsCommUndsRParUnds'MPY'Unds'KItem'Unds'Expr'Unds'Map{}
                  - default: fail
                    specializations:
                    - - LblCompare'LParUndsCommUndsRParUnds'MPY-SYNTAX'Unds'Expr'Unds'Expr'Unds'CmpOps{}
                      - default: fail
                        specializations:
                        - - Lbl'UndsCommUndsUnds'MPY-SYNTAX'Unds'CmpOps'Unds'CmpOp'Unds'CmpOps{}
                          - default: null
                            specializations:
                            - - LblCmpOp'LParUndsCommUndsRParUnds'MPY-SYNTAX'Unds'CmpOp'Unds'String'Unds'Expr{}
                              - default: fail
                                specializations:
                                - - Lbl'Stop'List'LBraQuotUndsCommUndsUnds'MPY-SYNTAX'Unds'CmpOps'Unds'CmpOp'Unds'CmpOps'QuotRBraUnds'CmpOps{}
                                  - action:
                                    - 547
                                    - - - ['1', '1']
                                        - STRING.String
                                      - - ['1', '0', '0', '0', '1']
                                        - STRING.String
                                      - - ['1', '0', '1']
                                        - STRING.String
                                      - - ['2', '0', '1']
                                        - STRING.String
                                      - - ['3', '0', '1']
                                        - STRING.String
                                      - - ['4', '0', '1']
                                        - STRING.String
                                      - - ['0', '0', '0', '0', '0', '0', '1']
                                        - STRING.String
                                      - - ['1', '0', '1', '0', '0', '0', '0', '0',
                                          '1']
                                        - STRING.String
                                      - - ['0', '0', '1', '0', '0', '0', '0', '0',
                                          '1']
                                        - STRING.String
                                      - - ['1', '0', '0', '0', '0', '1']
                                        - MAP.Map
                                  - []
                                sort: STRING.String
                                occurrence: ['1', '1', '0', '0', '0', '0', '0', '1']
                              - [STRING.String, STRING.String]
                            sort: STRING.String
                            occurrence: ['0', '1', '0', '0', '0', '0', '0', '1']
                          - [STRING.String, STRING.String]
                        sort: STRING.String
                        occurrence: ['1', '0', '0', '0', '0', '0', '1']
                      - [STRING.String, STRING.String]
                    sort: STRING.String
                    occurrence: ['0', '0', '0', '0', '0', '1']
                  - [STRING.String, MAP.Map]
                sort: STRING.String
                occurrence: ['0', '0', '0', '0', '1']
              - [STRING.String, STRING.String]
            sort: STRING.String
            occurrence: ['0', '0', '0', '1']
          - [STRING.String]
        sort: STRING.String
        occurrence: ['0', '0', '1']
      - [STRING.String, STRING.String, STRING.String, STRING.String, STRING.String]
    sort: STRING.String
    occurrence: ['0', '1']
  - [STRING.String, STRING.String]
sort: STRING.String
occurrence: ['1']
