default: null
specializations:
- - Lbl'-LT-'generatedTop'-GT-'{}
  - default: null
    specializations:
    - - Lbl'-LT-'mpy'-GT-'{}
      - default: null
        specializations:
        - - Lbl'-LT-'k'-GT-'{}
          - default: fail
            specializations:
            - - kseq{}
              - default: fail
                specializations:
                - - inj{SortPyVal{}, SortKItem{}}
                  - default: fail
                    specializations:
                    - - LblVInt'LParUndsRParUnds'MPY'Unds'PyVal'Unds'Int{}
                      - args:
                        - - &id001 ['0', '0', '0', '0', '0', '0', '1']
                          - INT.Int
                        next:
                          default: fail
                          specializations:
                          - - '1'
                            - args:
                              - - *id001
                                - INT.Int
                              - - [lit, '0', MINT.MInt 64]
                                - MINT.MInt 64
                              next:
                                default: fail
                                specializations:
                                - - '1'
                                  - default: fail
                                    specializations:
                                    - - kseq{}
                                      - default: fail
                                        specializations:
                                        - - LblsubscriptRightK'LParUndsRParUnds'MPY'Unds'KItem'Unds'PyVal{}
                                          - default: fail
                                            specializations:
                                            - - LblVList'LParUndsRParUnds'MPY'Unds'PyVal'Unds'Ints{}
                                              - default: fail
                                                specializations:
                                                - - Lbl'UndsSClnUndsUnds'MPY'Unds'Ints'Unds'Int'Unds'Ints{}
                                                  - action:
                                                    - 571
                                                    - - - ['1', '1']
                                                        - STRING.String
                                                      - - ['1', '1', '0', '0', '0',
                                                          '1']
                                                        - STRING.String
                                                      - - ['0', '0', '0', '0', '1',
                                                          '0', '0', '0', '1']
                                                        - INT.Int
                                                      - - ['1', '0', '1']
                                                        - STRING.String
                                                      - - ['2', '0', '1']
                                                        - STRING.String
                                                      - - ['3', '0', '1']
                                                        - STRING.String
                                                      - - ['4', '0', '1']
                                                        - STRING.String
                                                      - - ['1', '0', '0', '0', '1',
                                                          '0', '0', '0', '1']
                                                        - STRING.String
                                                  - [INT.Int, STRING.String]
                                                sort: STRING.String
                                                occurrence: ['0', '0', '0', '1', '0',
                                                  '0', '0', '1']
                                              - [STRING.String]
                                            sort: STRING.String
                                            occurrence: ['0', '0', '1', '0', '0',
                                              '0', '1']
                                          - [STRING.String]
                                        sort: STRING.String
                                        occurrence: ['0', '1', '0', '0', '0', '1']
                                      - [STRING.String, STRING.String]
                                    sort: STRING.String
                                    occurrence: ['1', '0', '0', '0', '1']
                                  - []
                                bitwidth: 64
                                sort: MINT.MInt 64
                                occurrence: &id002 ['0', '0', '0', '0', '0', '0',
                                  '0', '1']
                              function: hook_INT_limb
                              sort: MINT.MInt 64
                              occurrence: *id002
                            - []
                          bitwidth: 32
                          sort: MINT.MInt 32
                          occurrence: &id003 [size, '0', '0', '0', '0', '0', '0',
                            '1']
                        function: hook_INT_size_int
                        sort: MINT.MInt 32
                        occurrence: *id003
                      - [INT.Int]
                    sort: STRING.String
                    occurrence: ['0', '0', '0', '0', '0', '1']
                  - [STRING.String]
                sort: STRING.String
                occurrence: ['0', '0', '0', '0', '1']
              - [STRING.String, STRING.String]
            sort: STRING.String
            occurrence: ['0', '0', '0', '1']
          - [STRING.String]
        sort: STRING.String
        occurrence: ['0', '0', '1']
      - [STRING.String, STRING.String, STRING.String, STRING.String, STRING.String]
    sort: STRING.String
    occurrence: ['0', '1']
  - [STRING.String, STRING.String]
sort: STRING.String
occurrence: ['1']
