default: null
specializations:
- - Lbl'-LT-'generatedTop'-GT-'{}
  - default: null
    specializations:
    - - Lbl'-LT-'mpy'-GT-'{}
      - default: null
        specializations:
        - - Lbl'-LT-'k'-GT-'{}
          - default: fail
            specializations:
            - - kseq{}
              - default: fail
                specializations:
                - - Lblexec'LParUndsCommUndsRParUnds'MPY'Unds'KItem'Unds'Stmts'Unds'Map{}
                  - default: fail
                    specializations:
                    - - Lbl'UndsUndsUnds'MPY-SYNTAX'Unds'Stmts'Unds'Stmt'Unds'Stmts{}
                      - default: fail
                        specializations:
                        - - LblReturn'LParUndsRParUnds'MPY-SYNTAX'Unds'Stmt'Unds'Expr{}
                          - action:
                            - 556
                            - - - ['1', '1']
                                - STRING.String
                              - - ['1', '0', '0', '0', '1']
                                - STRING.String
                              - - ['1', '0', '0', '0', '0', '0', '1']
                                - STRING.String
                              - - ['1', '0', '1']
                                - STRING.String
                              - - ['2', '0', '1']
                                - STRING.String
                              - - ['3', '0', '1']
                                - STRING.String
                              - - ['4', '0', '1']
                                - STRING.String
                              - - ['0', '0', '0', '0', '0', '0', '0', '1']
                                - STRING.String
                              - - ['1', '0', '0', '0', '0', '1']
                                - MAP.Map
                          - [STRING.String]
                        sort: STRING.String
                        occurrence: ['0', '0', '0', '0', '0', '0', '1']
                      - [STRING.String, STRING.String]
                    sort: STRING.String
                    occurrence: ['0', '0', '0', '0', '0', '1']
                  - [STRING.String, MAP.Map]
                sort: STRING.String
                occurrence: ['0', '0', '0', '0', '1']
              - [STRING.String, STRING.String]
            sort: STRING.String
            occurrence: ['0', '0', '0', '1']
          - [STRING.String]
        sort: STRING.String
        occurrence: ['0', '0', '1']
      - [STRING.String, STRING.String, STRING.String, STRING.String, STRING.String]
    sort: STRING.String
    occurrence: ['0', '1']
  - [STRING.String, STRING.String]
sort: STRING.String
occurrence: ['1']
