name = "klean-114-minsubarraysum"
version = "0.1.0"
defaultTargets = ["Klean114Minsubarraysum"]
weakLeanArgs = [
    "-D maxHeartbeats=10000000"
]

buildDir = "/tmp/klean-generated-build"
moreLeanArgs = ["-D maxRecDepth=100000", "-s", "65536"]

[[lean_lib]]
name = "Klean114Minsubarraysum"
