name = "klean-68-pluck"
version = "0.1.0"
defaultTargets = ["Klean68Pluck"]
weakLeanArgs = [
    "-D maxHeartbeats=10000000"
]

buildDir = "/tmp/klean-generated-build"

[[lean_lib]]
name = "Klean68Pluck"
