#!/usr/bin/env python3
"""Produce an exhaustive, line-addressed K declaration/rule inventory."""

from __future__ import annotations

import re
from collections import Counter
from pathlib import Path


ROOT = Path("/tmp/audit-work/reconstruction")
OUT = Path("/audit-output/evidence/rule_inventory.md")
START = re.compile(
    r"^\s*(configuration|syntax|rule|claim|context|alias)\b"
)


def normalized(block: list[str]) -> str:
    pieces = []
    for raw in block:
        code = raw.split("//", 1)[0].strip()
        if code:
            pieces.append(code)
    return " ".join(pieces)


def tags(kind: str, statement: str) -> list[str]:
    found: list[str] = []
    if kind == "syntax":
        for tag in (
            "function", "total", "functional", "symbol",
            "no-evaluators", "macro-rec", "macro",
        ):
            if re.search(rf"\b{re.escape(tag)}\b", statement):
                found.append(tag)
        if "no-evaluators" in found:
            found.append("opaque")
    elif kind == "rule":
        priority = re.search(r"priority\((\d+)\)", statement)
        if priority:
            found.append(f"priority({priority.group(1)})")
        for tag in ("simplification", "concrete", "owise", "anywhere"):
            if re.search(rf"\b{tag}\b", statement):
                found.append(tag)
        if not found:
            found.append("ordinary")
    elif kind == "claim":
        if "functional" in statement:
            found.append("functional")
        else:
            found.append("reachability")
    return found


USED_FIXED_FILES = {
    "semantics.k",
    "semantics/syntax.k",
    "semantics/core.k",
    "semantics/iter.k",
    "semantics/operators.k",
    "semantics/int.k",
    "semantics/str.k",
    "semantics/list.k",
    "semantics/tuple.k",
    "semantics/controls.k",
    "semantics/functions.k",
    "semantics/builtins.k",
    "semantics/call.k",
    "semantics/sort.k",
}


def assessment(relative: Path, line: int, kind: str, statement: str) -> str:
    name = str(relative)
    if name == "verification.k":
        if kind == "rule" and line == 71:
            return "REJECT—unsound operational bridge; see witnesses 18/19/21"
        if kind in {"rule", "syntax"}:
            return "ACCEPT—truthful definition, structural encoding, or exact macro"
    if name == "spec.k":
        return "TARGET—reachability obligation, not an assumed semantic rule"
    if name.startswith("reference-semantics/"):
        fixed_name = name.removeprefix("reference-semantics/")
        if "no-evaluators" in statement:
            if fixed_name == "semantics/sort.k" and (
                "sortVS(" in statement or "sortKeyVS(" in statement
            ):
                return "TRUST—used result-bearing supplied sort primitive"
            return "TRUST—unused supplied opaque primitive"
        if fixed_name == "semantics/concrete.k":
            return "ACCEPT—reviewed concrete-only supplied-semantics rule"
        if fixed_name in USED_FIXED_FILES:
            return "ACCEPT—reviewed fixed-semantics file on the used execution slice"
        return "ACCEPT—reviewed supplied-semantics declaration/rule; unreachable here"
    return "REVIEWED"


paths = sorted((ROOT / "reference-semantics").rglob("*.k"))
paths.extend([ROOT / "verification.k", ROOT / "spec.k"])
summary: Counter[str] = Counter()
sections: list[str] = [
    "# Exhaustive K declaration and rule inventory",
    "",
    "Generated by `evidence/inventory_k.py`. Each item contains the source "
    "line, declaration class, relevant attributes, and its whitespace-"
    "normalized complete block. `ACCEPT` records the static decision, `TRUST` "
    "marks an explicit supplied-semantics boundary, `TARGET` marks claims, "
    "and `REJECT` marks the candidate defect.",
    "",
]

for path in paths:
    lines = path.read_text(encoding="utf-8").splitlines()
    starts: list[tuple[int, str]] = []
    for index, line in enumerate(lines):
        match = START.match(line)
        if match:
            starts.append((index, match.group(1)))
    sections.extend([f"## `{path.relative_to(ROOT)}`", ""])
    if not starts:
        sections.extend(["No local configuration, syntax, rule, or claim.", ""])
        continue
    for offset, (start, kind) in enumerate(starts):
        end = starts[offset + 1][0] if offset + 1 < len(starts) else len(lines)
        for candidate in range(start + 1, end):
            if lines[candidate].strip() == "endmodule":
                end = candidate
                break
        statement = normalized(lines[start:end])
        item_tags = tags(kind, statement)
        summary[kind] += 1
        for tag in item_tags:
            summary[f"{kind}:{tag}"] += 1
        tag_text = ", ".join(item_tags) if item_tags else "declaration"
        relative = path.relative_to(ROOT)
        item_assessment = assessment(relative, start + 1, kind, statement)
        summary[f"assessment:{item_assessment.split('—', 1)[0]}"] += 1
        sections.append(
            f"- `{relative}:{start + 1}` — "
            f"**{kind}** ({tag_text}); **{item_assessment}**: `{statement}`"
        )
    sections.append("")

sections.extend([
    "## Totals",
    "",
])
for key in sorted(summary):
    sections.append(f"- `{key}`: {summary[key]}")
sections.append("")

OUT.write_text("\n".join(sections), encoding="utf-8")
print(f"inventory_path={OUT}")
print(f"files={len(paths)}")
for key in sorted(summary):
    print(f"{key}={summary[key]}")
