name = "klean-90-next-smallest"
version = "0.1.0"
defaultTargets = ["Klean90NextSmallest"]
weakLeanArgs = [
    "-D maxHeartbeats=10000000"
]

buildDir = "/tmp/klean-generated-build"

[[lean_lib]]
name = "Klean90NextSmallest"
