name = "klean-156-int-to-mini-roman"
version = "0.1.0"
defaultTargets = ["Klean156IntToMiniRoman"]
weakLeanArgs = [
    "-D maxHeartbeats=10000000"
]

buildDir = "/tmp/klean-generated-build"
moreLeanArgs = ["-D maxRecDepth=100000", "-s", "65536"]

[[lean_lib]]
name = "Klean156IntToMiniRoman"
