name = "klean-143-words-in-sentence"
version = "0.1.0"
defaultTargets = ["Klean143WordsInSentence"]
weakLeanArgs = [
    "-D maxHeartbeats=10000000"
]

buildDir = "/tmp/klean-generated-build"
moreLeanArgs = ["-D maxRecDepth=100000", "-s", "65536"]

[[lean_lib]]
name = "Klean143WordsInSentence"
