#!/usr/bin/env python3
"""Produce a line-bounded inventory of K declarations and rule-like statements."""

from __future__ import annotations

import re
import sys
from collections import Counter
from pathlib import Path


START = re.compile(
    r"^(?P<indent>[ \t]+)(?P<kind>"
    r"configuration|syntax|rule|claim|context|alias"
    r")\b"
)
BOUNDARY = re.compile(
    r"^(?:[ \t]+(?:configuration|syntax|rule|claim|context|alias)\b"
    r"|[ \t]*(?:module|endmodule|imports|requires)\b)"
)


def classify(kind: str, statement: str) -> str:
    tags = [kind]
    if kind == "syntax":
        for attribute in ("function", "total", "functional", "hook", "symbol"):
            if re.search(rf"\b{attribute}\b", statement):
                tags.append(attribute)
        if re.search(r"\btoken\b", statement):
            tags.append("token")
        if re.search(r"\bpriorit(?:y|ies)\b", statement):
            tags.append("priority-declaration")
    elif kind == "rule":
        if re.search(r"\bsimplification\b", statement):
            tags.append("simplification")
        else:
            tags.append("ordinary")
        if re.search(r"\bpriority\s*\(", statement):
            tags.append("priority-rule")
        if re.search(r"\bowise\b", statement):
            tags.append("owise")
        if re.search(r"\banywhere\b", statement):
            tags.append("anywhere")
        if re.search(r"\bmacro\b", statement):
            tags.append("macro")
    return ",".join(tags)


def inventory(path: Path):
    lines = path.read_text(encoding="utf-8").splitlines()
    statements = []
    index = 0
    while index < len(lines):
        match = START.match(lines[index])
        if match is None:
            index += 1
            continue
        indent_width = len(match.group("indent").expandtabs(8))
        # Only module-level statements are indented one logical level. Content
        # nested inside a statement is more deeply indented.
        if indent_width > 2:
            index += 1
            continue
        kind = match.group("kind")
        start = index
        index += 1
        while index < len(lines):
            next_match = START.match(lines[index])
            if next_match is not None:
                next_indent = len(next_match.group("indent").expandtabs(8))
                if next_indent <= 2:
                    break
            if re.match(r"^[ \t]*endmodule\b", lines[index]):
                break
            index += 1
        end = index
        text = "\n".join(lines[start:end]).rstrip()
        statements.append((start + 1, end, kind, classify(kind, text), text))
    return statements


def main() -> int:
    if len(sys.argv) < 2:
        print(f"usage: {sys.argv[0]} FILE_OR_DIRECTORY [...]", file=sys.stderr)
        return 64

    files = []
    for raw_path in sys.argv[1:]:
        path = Path(raw_path)
        if path.is_dir():
            files.extend(sorted(path.rglob("*.k")))
        else:
            files.append(path)
    files = sorted(dict.fromkeys(files))

    totals = Counter()
    print("# Exhaustive K declaration and rule inventory")
    print()
    print("Generated by inventory_k.py from fresh scratch source copies.")
    for path in files:
        statements = inventory(path)
        local = Counter(item[2] for item in statements)
        print()
        print(f"## {path}")
        print()
        print(
            "Local counts: "
            + ", ".join(f"{kind}={local[kind]}" for kind in sorted(local))
        )
        print()
        for start, end, kind, classification, text in statements:
            totals[kind] += 1
            for tag in classification.split(",")[1:]:
                totals[f"{kind}:{tag}"] += 1
            print(f"### lines {start}-{end}: {classification}")
            print()
            print("```k")
            print(text)
            print("```")
            print()

    print("## Totals")
    print()
    for key in sorted(totals):
        print(f"- {key}: {totals[key]}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
