name = "klean-7-filter-by-substring"
version = "0.1.0"
defaultTargets = ["Klean7FilterBySubstring"]
weakLeanArgs = [
    "-D maxHeartbeats=10000000"
]

buildDir = "/tmp/klean-generated-build"

[[lean_lib]]
name = "Klean7FilterBySubstring"
