default: null
specializations:
- - Lbl'-LT-'generatedTop'-GT-'{}
  - default: null
    specializations:
    - - Lbl'-LT-'mpy'-GT-'{}
      - default: null
        specializations:
        - - Lbl'-LT-'k'-GT-'{}
          - default: fail
            specializations:
            - - kseq{}
              - default: fail
                specializations:
                - - inj{SortPyVal{}, SortKItem{}}
                  - default: fail
                    specializations:
                    - - LblBoolV'LParUndsRParUnds'MPY-SYNTAX'Unds'PyVal'Unds'Bool{}
                      - default: fail
                        specializations:
                        - - '0'
                          - default: fail
                            specializations:
                            - - kseq{}
                              - default: fail
                                specializations:
                                - - Lblbranch'LParUndsCommUndsRParUnds'SEMANTIC'Unds'KItem'Unds'Stmts'Unds'Stmts{}
                                  - action:
                                    - 339
                                    - - - ['1', '1']
                                        - STRING.String
                                      - - ['1', '1', '0', '0', '0', '1']
                                        - STRING.String
                                      - - ['0', '0', '1', '0', '0', '0', '1']
                                        - STRING.String
                                      - - ['1', '0', '1']
                                        - STRING.String
                                      - - ['2', '0', '1']
                                        - STRING.String
                                      - - ['3', '0', '1']
                                        - STRING.String
                                      - - ['4', '0', '1']
                                        - STRING.String
                                      - - ['1', '0', '1', '0', '0', '0', '1']
                                        - STRING.String
                                  - [STRING.String, STRING.String]
                                sort: STRING.String
                                occurrence: ['0', '1', '0', '0', '0', '1']
                              - [STRING.String, STRING.String]
                            sort: STRING.String
                            occurrence: ['1', '0', '0', '0', '1']
                          - []
                        bitwidth: 1
                        sort: BOOL.Bool
                        occurrence: ['0', '0', '0', '0', '0', '0', '1']
                      - [BOOL.Bool]
                    sort: STRING.String
                    occurrence: ['0', '0', '0', '0', '0', '1']
                  - [STRING.String]
                sort: STRING.String
                occurrence: ['0', '0', '0', '0', '1']
              - [STRING.String, STRING.String]
            sort: STRING.String
            occurrence: ['0', '0', '0', '1']
          - [STRING.String]
        sort: STRING.String
        occurrence: ['0', '0', '1']
      - [STRING.String, STRING.String, STRING.String, STRING.String, STRING.String]
    sort: STRING.String
    occurrence: ['0', '1']
  - [STRING.String, STRING.String]
sort: STRING.String
occurrence: ['1']
