default: null
specializations:
- - Lbl'-LT-'generatedTop'-GT-'{}
  - default: null
    specializations:
    - - Lbl'-LT-'mpy'-GT-'{}
      - default: null
        specializations:
        - - Lbl'-LT-'k'-GT-'{}
          - default: fail
            specializations:
            - - kseq{}
              - default: fail
                specializations:
                - - inj{SortStmt{}, SortKItem{}}
                  - default: fail
                    specializations:
                    - - LblFuncDef'LParUndsCommUndsCommUndsRParUnds'MPY-SYNTAX'Unds'Stmt'Unds'String'Unds'Params'Unds'Stmts{}
                      - default: null
                        specializations:
                        - - LblParams'LParUndsRParUnds'MPY-SYNTAX'Unds'Params'Unds'Strings{}
                          - next:
                              args:
                              - - &id004 ['0', '0', '0', '0', '0', '0', '1']
                                - STRING.String
                              - - &id006 [lit, below_zero, STRING.String]
                                - STRING.String
                              next:
                                default: null
                                specializations:
                                - - '1'
                                  - default:
                                      default: fail
                                      specializations:
                                      - - Lbl'UndsCommUndsUnds'MPY-SYNTAX'Unds'Strings'Unds'String'Unds'Strings{}
                                        - default: fail
                                          specializations:
                                          - - Lbl'Stop'List'LBraQuotUndsCommUndsUnds'MPY-SYNTAX'Unds'Strings'Unds'String'Unds'Strings'QuotRBraUnds'Strings{}
                                            - next:
                                                args:
                                                - - &id001 ['0', '0', '1', '0', '0',
                                                    '0', '0', '0', '1']
                                                  - STRING.String
                                                - - &id003 [lit, operations, STRING.String]
                                                  - STRING.String
                                                next:
                                                  default: null
                                                  specializations:
                                                  - - '1'
                                                    - default:
                                                        action:
                                                        - 347
                                                        - - - ['1', '1']
                                                            - STRING.String
                                                          - - ['1', '0', '0', '0',
                                                              '1']
                                                            - STRING.String
                                                          - - ['1', '0', '1']
                                                            - STRING.String
                                                          - - ['2', '0', '1']
                                                            - STRING.String
                                                          - - ['3', '0', '1']
                                                            - STRING.String
                                                          - - ['4', '0', '1']
                                                            - STRING.String
                                                          - - ['2', '0', '0', '0',
                                                              '0', '0', '1']
                                                            - STRING.String
                                                      specializations: []
                                                      sort: STRING.String
                                                      occurrence: *id001
                                                    - []
                                                  - - '0'
                                                    - default: fail
                                                      specializations: []
                                                      sort: STRING.String
                                                      occurrence: ['0', '0', '1',
                                                        '0', '0', '0', '0', '0', '1']
                                                    - []
                                                  bitwidth: 1
                                                  sort: BOOL.Bool
                                                  occurrence: &id002 [eq, '0', '0',
                                                    '1', '0', '0', '0', '0', '0',
                                                    '1', and, lit, operations, STRING.String]
                                                function: hook_KEQUAL_eq
                                                sort: BOOL.Bool
                                                occurrence: *id002
                                              pattern: {hook: STRING.String, literal: operations}
                                              occurrence: *id003
                                              sort: STRING.String
                                            - []
                                          sort: STRING.String
                                          occurrence: ['1', '0', '1', '0', '0', '0',
                                            '0', '0', '1']
                                        - [STRING.String, STRING.String]
                                      sort: STRING.String
                                      occurrence: ['0', '1', '0', '0', '0', '0', '0',
                                        '1']
                                    specializations: []
                                    sort: STRING.String
                                    occurrence: *id004
                                  - []
                                - - '0'
                                  - default: fail
                                    specializations: []
                                    sort: STRING.String
                                    occurrence: ['0', '0', '0', '0', '0', '0', '1']
                                  - []
                                bitwidth: 1
                                sort: BOOL.Bool
                                occurrence: &id005 [eq, '0', '0', '0', '0', '0', '0',
                                  '1', and, lit, below_zero, STRING.String]
                              function: hook_KEQUAL_eq
                              sort: BOOL.Bool
                              occurrence: *id005
                            pattern: {hook: STRING.String, literal: below_zero}
                            occurrence: *id006
                            sort: STRING.String
                          - [STRING.String]
                        sort: STRING.String
                        occurrence: ['1', '0', '0', '0', '0', '0', '1']
                      - [STRING.String, STRING.String, STRING.String]
                    sort: STRING.String
                    occurrence: ['0', '0', '0', '0', '0', '1']
                  - [STRING.String]
                sort: STRING.String
                occurrence: ['0', '0', '0', '0', '1']
              - [STRING.String, STRING.String]
            sort: STRING.String
            occurrence: ['0', '0', '0', '1']
          - [STRING.String]
        sort: STRING.String
        occurrence: ['0', '0', '1']
      - [STRING.String, STRING.String, STRING.String, STRING.String, STRING.String]
    sort: STRING.String
    occurrence: ['0', '1']
  - [STRING.String, STRING.String]
sort: STRING.String
occurrence: ['1']
