default: null
specializations:
- - Lbl'-LT-'generatedTop'-GT-'{}
  - default: null
    specializations:
    - - Lbl'-LT-'mpy'-GT-'{}
      - default: null
        specializations:
        - - Lbl'-LT-'current'-GT-'{}
          - default: null
            specializations:
            - - Lbl'-LT-'k'-GT-'{}
              - default: fail
                specializations:
                - - kseq{}
                  - default: fail
                    specializations:
                    - - inj{SortPyVal{}, SortKItem{}}
                      - default: fail
                        specializations:
                        - - LblListV'LParUndsRParUnds'MPY-SYNTAX'Unds'PyVal'Unds'IntList{}
                          - default: fail
                            specializations:
                            - - kseq{}
                              - default: fail
                                specializations:
                                - - Lblloop'LParUndsRParUnds'SEMANTIC'Unds'KItem'Unds'Stmts{}
                                  - default: fail
                                    specializations:
                                    - - Lblcons'LParUndsCommUndsRParUnds'MPY-SYNTAX'Unds'IntList'Unds'Int'Unds'IntList{}
                                      - action:
                                        - 343
                                        - - - ['1', '1']
                                            - STRING.String
                                          - - ['1', '1', '0', '0', '0', '1']
                                            - STRING.String
                                          - - ['0', '3', '0', '1']
                                            - INT.Int
                                          - - ['1', '0', '1']
                                            - STRING.String
                                          - - ['0', '1', '0', '0', '0', '1']
                                            - STRING.String
                                          - - ['2', '0', '1']
                                            - STRING.String
                                          - - ['4', '0', '1']
                                            - STRING.String
                                          - - ['0', '0', '1', '0', '0', '0', '1']
                                            - STRING.String
                                          - - ['0', '0', '0', '0', '0', '0', '0',
                                              '1']
                                            - INT.Int
                                          - - ['1', '0', '0', '0', '0', '0', '0',
                                              '1']
                                            - STRING.String
                                      - [INT.Int, STRING.String]
                                    sort: STRING.String
                                    occurrence: ['0', '0', '0', '0', '0', '0', '1']
                                  - [STRING.String]
                                sort: STRING.String
                                occurrence: ['0', '1', '0', '0', '0', '1']
                              - [STRING.String, STRING.String]
                            sort: STRING.String
                            occurrence: ['1', '0', '0', '0', '1']
                          - [STRING.String]
                        sort: STRING.String
                        occurrence: ['0', '0', '0', '0', '0', '1']
                      - [STRING.String]
                    sort: STRING.String
                    occurrence: ['0', '0', '0', '0', '1']
                  - [STRING.String, STRING.String]
                sort: STRING.String
                occurrence: ['0', '0', '0', '1']
              - [STRING.String]
            sort: STRING.String
            occurrence: ['0', '0', '1']
          - [INT.Int]
        sort: STRING.String
        occurrence: ['3', '0', '1']
      - [STRING.String, STRING.String, STRING.String, STRING.String, STRING.String]
    sort: STRING.String
    occurrence: ['0', '1']
  - [STRING.String, STRING.String]
sort: STRING.String
occurrence: ['1']
