#!/usr/bin/env python3
"""Regenerate the submitted MPY artifact with the trusted translator."""

from __future__ import annotations

import hashlib
import subprocess
from pathlib import Path


TRUSTED_TRANSLATOR = Path("/tmp/audit-work/reference/py2mpy.py")
SOLUTION_PY = Path("/tmp/audit-work/candidate/solution.py")
SUBMITTED_MPY = Path("/tmp/audit-work/candidate/solution.mpy")
REGENERATED_MPY = Path("/tmp/audit-work/regenerated-solution.mpy")


def digest(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def main() -> int:
    completed = subprocess.run(
        ["python3", str(TRUSTED_TRANSLATOR), str(SOLUTION_PY)],
        check=False,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    REGENERATED_MPY.write_bytes(completed.stdout)
    print(
        "translator command: "
        f"python3 {TRUSTED_TRANSLATOR} {SOLUTION_PY} > {REGENERATED_MPY}"
    )
    print(f"translator exit status: {completed.returncode}")
    print(f"translator stderr: {completed.stderr.decode(errors='replace')!r}")
    submitted = SUBMITTED_MPY.read_bytes()
    regenerated = REGENERATED_MPY.read_bytes()
    print(f"submitted bytes={len(submitted)} sha256={digest(submitted)}")
    print(f"regenerated bytes={len(regenerated)} sha256={digest(regenerated)}")
    print(f"byte-identical: {submitted == regenerated}")
    return 0 if completed.returncode == 0 and submitted == regenerated else 1


if __name__ == "__main__":
    raise SystemExit(main())
